Repository Acanguven/rapidash, pull requests merged in 2020-02, with the labels that each got.

#8 Feature/local cli run solution
  .circleci/config.yml
  package-lock.json
  package.json
  src/benchmark.ts
  src/registry.ts
  src/solution-cli.ts
  template/docs/submit-a-solution.md
  template/npm/package.json
Labels: enhancement

#19 Feature: Add tail recursive factorial solution
  src/functions/factorial.ts
Labels: Method, Solution

#18 Feature: Add palindrome solution
  src/functions/index.ts
  src/functions/is-palindrome.ts
Labels: Method, Solution

#24 Feature/multi bench support
  package-lock.json
  package.json
  src/benchmark.ts
  src/functions/factorial.ts
  src/solution.ts
  template/docs/function-template.md
  tsconfig.json
Labels: enhancement

#16 fibonacci golden ratio solution added
  .gitignore
  src/functions/fibonacci.ts
Labels: Solution

#15 Add equal & isString
  README.md
  package-lock.json
  package.json
  src/functions/equal.ts
  src/functions/index.ts
  src/functions/is-string.ts
  src/functions/times.ts
Labels: Method, Solution
